### PR TITLE
Change param validation to verbose output

### LINKED ISSUE #97: Unable to find or install app, searching by ID or name fails.
HELP

### PR DESCRIPTION
**Pull request by hjorslev**
## Description

Fixes #97 

Change the parameter validation to just show a verbose output if the application isn't found instead of throwing an error.

## Type of change

- [ ] 📖 [Docs]
- [x] 🪲 [Fix]
- [ ] ⚠️ [Security fix]
- [ ] ♻️ [Refactor]
- [ ] 🎉 [Feature]
- [ ] ✨ Enhancement
- [ ] 🌟 [Breaking change]

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added Pester tests that covers the added cmdlets

### CODE REVIEW

**Comment by OTonGitHub** [comment]
Hi, so is there a way to verify if the app exists, or just relying on the results from `steamcmd` command.

**Comment by hjorslev** [comment]
Relying on the results from SteamCMD (for now at least) so you are able to install it without being blocked by the parameter validation.

But ARK has for sure been in the app list via the Steam Web API. I can see that I use it as an example in `Update-SteamApp`.

**Comment by OTonGitHub** [comment]
It was, it's really weird, I think we need another way of fetching it or just see what's up with the SteamAPI. I will make a fork and try it out, is there a recommended way of testing this repo? I'd like to contribute if possible. Since its open source and if contributors are welcome.

**Comment by hjorslev** [comment]
You are welcome to contribute!

I develop the commands locally and then when I write a corresponding Pester test (those are found in Tests\Unit). Then I create a PR that hopefully passes all the Pester tests. This is especially useful if reworking a cmdlet or something similar because then you can see if something breaks.

Only trouble as of now is that there are no SteamPS.psm1 file which would need to be created on your machine if you want to import the module locally. As of now SteamPS.psm1 are only created in the CI build.

**Pull request merged**
