### PR TITLE
Support the server challenge request (Linux based servers), fixes #47

### LINKED ISSUE #47: Get-SteamServerInfo Cmdlet fails for linux based "The Isle" servers
# Describe "Module Bug or Issue"
Get-SteamServerInfo Cmdlet works for windows based game servers (The Isle) but not for linux based.

## Context "The Problem"
Lately the The Isle game developers have introduced new servers which are now based on linux (that is the only change that I know of). For these servers the query fails:
```
PS c:\> Get-SteamServerInfo -IPAddress '34.244.178.139' -Port 27015
Exception calling "ReadByte" with "0" argument(s): "Unable to read beyond the end of the stream."
At C:\Program Files\WindowsPowerShell\Modules\SteamPS\3.2.1\Private\Server\Get-PacketString.ps1:31 char:13
+             $byte = $Stream.ReadByte()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : EndOfStreamException
```
This error loops endlessly and you have to ctrl+c to stop the Cmdlet.

## Context "Expected Behavior"
It is possible to query this server (it is based on windows):
```
PS c:\> Get-SteamServerInfo -IPAddress '3.250.191.172' -Port 27015

Protocol      : 17
ServerName    : UP4 - Mechanic Test - EU 1
Map           : Isla_Spiro
InstallDir    : theisle
GameName      : Evrima 0.8.29.04
AppID         : 0
Players       : 75
MaxPlayers    : 75
Bots          : 0
ServerType    : Dedicated
Environment   : Windows
Visibility    : Public
VAC           : Secured
Version       : 0.8.29.04
ExtraDataFlag : 177
IPAddress     : 3.250.191.172
Port          : 27015
```

## Context "Additional Information"

```
PS c:\> Get-Module -Name SteamPS -ListAvailable | Select-Object -Property Name, Version

Name    Version
----    -------
SteamPS 3.2.1


PS c:\> $PSVersionTable | Out-String

Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### PR DESCRIPTION
**Pull request by ThePoShWolf**
# PR Summary

Fixes #47 - Supports the server challenge (https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO). Tested and still works on Windows based servers.

## Context

When querying a Linux based Rust server, I was getting a 9 bytes response which turned out to be the 4 byte header, the byte indicating a challenge ('A' or 0x41) followed by the challenge bytes themselves. To handle this and get the requested data, the client needs to send the query again with the challenge appended.

See the steam docs for further details.

## Changes

If the first byte of the stream (after the headers) is the challenge indicator, then resend the original query with the challenge bytes appended.

This change was made it `Get-SteamServerInfo.ps1`.

## Checklist

- [X] Pull Request has a meaningful title.
- [X] Summarised changes.
- [X] Pull Request is ready to merge & is not WIP.
- [X] Added tests / only testable interactively.
  - Make sure you add a new test if old tests do not effectively test the code changed.
- [X] Added documentation / opened issue to track adding documentation at a later date.

### CODE REVIEW

**Comment by hjorslev** [comment]
Thans so much for this PR!

I will merge and release it this weekend 😊

**Comment by hjorslev** [comment]
@ThePoShWolf 

After the new release when I query my server it skips the first letter of the server name:
```
Protocol      : 83
ServerName    : AS Proving Ground 12 (EU)
Map           : PowerStation
InstallDir    : groundbranch
GameName      : Ground Branch
AppID         : 0
Players       : 0
MaxPlayers    : 10
Bots          : 0
ServerType    : Dedicated
Environment   : Windows
Visibility    : Public
VAC           : Unsecured
Version       : 1.0.0.0
ExtraDataFlag : 177
IPAddress     : 185.15.73.207
Port          : 27015
```

If I change `$ReceivedData = $Client.Receive([Ref]$IPEndpoint) | Select-Object -Skip 4` to $ReceivedData = `$Client.Receive([Ref]$IPEndpoint) | Select-Object -Skip 3` it seems to work.

Could I get you to review that solution for me and test against a linux based server?

**Comment by ThePoShWolf** [comment]
@hjorslev - That is strange. Here's the output if I `-Skip 3`:

```text
Protocol      : 73
ServerName    : ◄Land of the Toddomites
Map           : Procedural Map
InstallDir    : rust
GameName      : Rust
AppID         : 0
Players       : 0
MaxPlayers    : 10
Bots          : 0
ServerType    : Dedicated
Environment   : Linux
Visibility    : Public
VAC           : Secured
Version       : 2336
ExtraDataFlag : 177
IPAddress     : 20.236.47.160
Port          : 28015
```

There is an extra character in the server name.

If I switch back to `-Skip 4`, then the protocol changes as well:

```text
Protocol      : 17
ServerName    : Land of the Toddomites
...
```

I'm not sure what is happening, but when I have more time this weekend I can try digging into that a bit deeper. Feel free to use my server IP above for testing.

**Comment by ThePoShWolf** [comment]
@hjorslev I figured it out. In `Get-SteamServerInfo` line 85, the if statement is doing a `ReadByte()`, so it moves the position forward by one. All it takes to fix is an else with: `$Stream.BaseStream.Position = 0`. I'll submit a new PR.

**Comment by ThePoShWolf** [comment]
#53 submitted.

**Pull request merged**
